<?php

define('ISLANDORA_BOOK_BATCH_FLAG_URI', 'info:islandora/islandora-system:def/batch-flag#');

function islandora_book_batch_islandora_bookCModel_islandora_ingest_post_ingest($object) {
  if ($object->relationships->get(ISLANDORA_BOOK_BATCH_FLAG_URI, 'create_pdf', 'true', TRUE)) {
    // Generate the PDF if the flag was set.
    module_load_include('inc', 'islandora_book', 'includes/book.batch');
    module_load_include('inc', 'islandora_book', 'includes/utilities');
    $batch = islandora_book_create_pdf_batch($object, array_keys(islandora_book_get_pages($object)), array(
      '-density' => '96',
      '-compress' => 'LZW',
    ));

    $batch['operations'][] = array('islandora_book_batch_remove_pdf_flag', array($object));

    batch_set($batch);

    $batch = batch_get();
    if (!isset($batch['id'])) {
      // Start the batch, as it does not seem to be running.
      batch_process();
    }
  }
}

/**
 * A batch operation to remove the flag.
 */
function islandora_book_batch_remove_pdf_flag($object, &$context) {
  $object->relationships->remove(ISLANDORA_BOOK_BATCH_FLAG_URI, 'create_pdf', 'true', TRUE);
}
